name: Measure code coverage

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        timeout-minutes: 30
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'
          cache: maven

      - name: Build and Test
        if: always()
        run: mvn -B package --file pom.xml
        continue-on-error: true

      - name: Upload Report
        uses: 'actions/upload-artifact@v3'
        with:
          name: jacoco-report
          path: |
            ${{ github.workspace }}/docs/jacoco/jacoco.xml
            ${{ github.workspace }}/docs/jacoco/index.html

      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: ${{ github.workspace }}/docs/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 50
          min-coverage-changed-files: 40
          title: '# :recycle: Coverage Report'
          update-comment: true
          pass-emoji: ':green_circle:'
          fail-emoji: ':red_circle:'